### ISSUE TITLE
Azure EventHub Checkpointing

### ISSUE THREAD

**Issue by R00iBaard** [Daniel-Krzyczkowski/AzureDeveloperTemplates#5]
Hi there,

Firstly thanks so much for sharing this project.
I am just a little confused where your EventHub Checkpointing happens?

Each time I run my application I am obviously re processing all the old events once again as expected as no checkpointing.

**Comment by Daniel-Krzyczkowski** [comment]
Hi,

Thank you for a kind words! 
When it comes to the sample - there is not checkpointing included. This is just a base sample to present how to use new C# SDK for Event Hub.
You can read more about migration for checkpoint functionality here:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-event-processor-checkpoints

**Comment by R00iBaard** [comment]
Hey,

Ok great thanks!
